name: Debug
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tmate
      env:
        ARGOCD_REPO_SSH: ${{ secrets.ARGOCD_REPO_SSH }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      uses: mxschmitt/action-tmate@v2
