# This is a basic workflow to help you get started with Actions

name: Deploy Prod

on:
  workflow_dispatch:

env:
  ECR: 081239602556.dkr.ecr.eu-central-1.amazonaws.com/polkapad-polkapad-api
  ROLE: "arn:aws:iam::081239602556:role/github-ecr-polkapad-polkapad-api"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - uses: actions/checkout@v3

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Set env
        run: |
          echo "TAG=${ECR}:${{ env.GIT_COMMIT_SHORT_SHA }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm ci

#      - name: Unit tests
#        run: npm run test
#
#      - name: E2e tests
#        run: npm run test:e2e
#
#      - name: Coverage test
#        run: npm run test:cov
#
      - name: Docker build
        run: docker build -t $TAG -f .github/workflows/Dockerfile .

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.ROLE }}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-central-1 # use your region here.

      - name: ECR login
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

      - name: Push image
        run: docker push $TAG
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

      - uses: kobtea/setup-jsonnet-action@v1

      - name: Clone Argo repo
        uses: actions/checkout@v3
        with:
          repository: 'polkapad/argocd'
          ref: main
          ssh-key: ${{ secrets.ARGOCD_REPO_SSH }}
          path: argo
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

      - name: Write TAG to argo
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          cd argo
          mkdir -p versions/${{github.repository_owner}}
          jsonnet libs/ci_image.libsonnet -A env=prod -A project=polkapad_api -A image="${TAG}" > out.json
          mv out.json env.json
          git config user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          git config user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          git add env.json && git commit -m "${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} ${{ env.GIT_COMMIT_SHORT_SHA }}" && git push || true

