name: Deploy Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ closed ]
  workflow_dispatch:

env:
  ECR: 636334651895.dkr.ecr.eu-central-1.amazonaws.com/grabberofficial-polkapad-api
  ROLE: "arn:aws:iam::636334651895:role/github-ecr-grabberofficial-polkapad-api"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Set env
        run: |
          echo "TAG=${ECR}:${{ env.GIT_COMMIT_SHORT_SHA }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm ci

#      - name: Unit tests
#        run: npm run test
#
#      - name: E2e tests
#        run: npm run test:e2e
#
#      - name: Coverage test
#        run: npm run test:cov
#
      - name: Docker build
        run: docker build -t $TAG -f .github/workflows/Dockerfile .

      - name: Push to ECR and Argo
        uses: ./.github/actions/argo-push
        with:
          aws-role: ${{ env.ROLE }}
          aws-ecr-uri: ${{ env.ECR }}
          ssh-key: ${{ secrets.ARGOCD_REPO_SSH }}
          environment: dev
          project: polkapad_api
          image: ${{ env.TAG }}

